name: Resuable Deploy
on: 
  workflow_call
    inputs:
      artifact-name:
        description: Name of the deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifacts@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output Information
        run: echo "Deploying..."

